version: '3.7'

services:
  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - ${SERVICE_PORT}:8000
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python

  python:
    build: ./python
    command: uwsgi --socket :8001 --module ${DJANGO_PROJECT_NAME}.wsgi --logto /tmp/uwsgi.log
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - TZ
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - 8001
    depends_on:
      - db

  db:
    image: mysql:8.0.22
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - TZ
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-store:

